# 2. Your Node.js application requires environment variables 
# stored in a ConfigMap named node-env-config. 
# How will you inject these variables into your pod?

apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: node-app
spec:
  containers:
    - name: app
      image: node:18
      envFrom:
        - configMapRef:
            name: node-env-config
