apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
    - name: db-client
      image: postgress
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=