# The monitoring team reports that production dashboards aren't 
# showing any traffic or metrics for nginx-based web servers.
# But the application team insists everything is running fine.
# What would you do as a DevOps engineer in this scenario?

apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx
    env: prod  
spec:
  containers:
  - name: nginx
    image: nginx:latest